name: Swift

on: [push, pull_request]

jobs:
  UICBuildTesting:
    runs-on: macos-latest
    steps:
     - uses: actions/checkout@v1
     - name: Install Dependences
       run: |
          pod repo update
          pod install
       shell: bash
     - name: Build for Testing
       run: xcodebuild build-for-testing CODE_SIGNING_ALLOWED=NO -workspace RealDeviceMap-UIControl.xcworkspace/ -scheme RealDeviceMap-UIControl -destination generic/platform=iOS
  ManagerBuildDebug:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Resolve
      working-directory: Manager
      run: swift package resolve
    - uses: actions/cache@v1
      with:
        path: Manager/.build
        key: ${{ runner.os }}-debug-spm-${{ hashFiles('Manager/Package.resolved') }}
    - name: Build
      working-directory: Manager
      run: swift build -v -c debug
    - name: Test
      working-directory: Manager
      run: swift test -v -c debug
  ManagerBuildRelease:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Resolve
      working-directory: Manager
      run: swift package resolve
    - uses: actions/cache@v1
      with:
        path:  Manager/.build
        key: ${{ runner.os }}-release-spm-${{ hashFiles('Manager/Package.resolved') }}
    - name: Build
      working-directory: Manager
      run: swift build -v -c release
